/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_admin_jn_JniUtils */

#ifndef _Included_com_admin_jn_JniUtils
#define _Included_com_admin_jn_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_admin_jn_JniUtils
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_admin_jn_JniUtils_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
